### ISSUE TITLE
readinessProbe

### ISSUE THREAD

**Issue by benjick** [mittwald/kube-httpcache#49]
I know this has been tried to be solved before but I think this warrants an open issue. Currently we're running a `livenessProbe` on a synthetic route which solves most of the problems, but as you know it doesn't really work with a `readinessProbe` due to the catch-22.

```vcl
if (req.url == "/varnish_healthz") {
    return (synth(200, "OK"));
}
```

I don't have the knowledge of go to implement something myself but if I can help in any other way I'm very eager to have this feature. This is such a great project in every other way - thanks for creating this!

**Describe the solution you'd like**
I would like to be able to run a `readinessProbe` on this StatefulSet.

**Describe alternatives you've considered**
One idea I was toying with was to run a shell script on the pod that returns *OK* for the first minute and then does a `curl` to `:80/varnish_healthz` after that but I couldn't install any packages in my derivative Dockerfile, I guess this is because of how the pod is cleaned to optimize the size.

**Comment by benjick** [comment]
Actually while writing this issue I got an idea. I added another backend that pointed to localhost making my vcl-file look like this (along with the synthetic from above):

```vcl
{{ range .Frontends }}
backend {{ .Name }} {
    .host = "{{ .Host }}";
    .port = "{{ .Port }}";
}
{{- end }}

backend default {
    .host = "localhost";
    .port = "80";
}
```

Then I made my StatefulSet have these:

```ts
livenessProbe: {
  // Kills the pod
  httpGet: {
    port: 80,
    path: '/varnish_healthz',
  },
  initialDelaySeconds: 30,
  periodSeconds: 5,
  failureThreshold: 5,
  successThreshold: 1,
},
readinessProbe: {
  // Sets the pod unready
  httpGet: {
    port: 80,
    path: '/varnish_healthz',
  },
  initialDelaySeconds: 10,
  periodSeconds: 1,
  failureThreshold: 1,
  successThreshold: 1,
},
```

and it seems to be working in my test environment, but is this safe to use in production or do you think it will break something?

**Comment by martin-helmich** [comment]
TBH, readiness probes in this context have been a mess for some time. 🤯  There were earlier attempts to implement these controller-side (#35) which failed due to design bugs (#36) and were rolled back (#37). Also, various strategies for VCL- or script/exec-based readiness checks have been suggested (like this one, and there also was a lengthy discussion in #36).

I need to admit that I've lost a bit of track of this one -- when I find the time, I'll see if I can work out (and document) a recommended approach for implementing readiness probes (and maybe push a revised version of #35, if need be).

@benjick In one of these issues, I remember seeing a suggestion to use the [`.spec.publishNotReadyAddresses` property](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#servicespec-v1-core) when defining the frontend service; I think that might at least alleviate the issue of Varnish not even starting (since the controller waits until frontend endpoints are available before starting Varnish -- which will not happen, if there's a readiness probe).

**Comment by benjick** [comment]
@martin-helmich thanks, I got it working. But I'm not sure it's enough. I think because we're using `directors.hash()` the request might still end up hitting a pod that is not ready
