### ISSUE TITLE
Allow for watching and templating the kube-httpcache service

### ISSUE THREAD

**Issue by znorris** [mittwald/kube-httpcache#7]
Thank you for building this and making it available to the rest of us!

I'm looking to build a varnish cluster that will self route to other varnish nodes using the hash director. To do so I need kube-httpcache to monitor its own endpoint, watch it for updates, and update my vcl template with the backends that represent the varnish nodes.

My first thought was to add an additional flag to tell the controller what service represents the controller pods. Something like, `-varnish-backend-service` and `{{ .Varnish.Hosts }}`. However, if you think it's possible the number of watched services will continue to expand there may be better solutions.

Also, it wasn't clear to me what `.PrimaryBackend` vs `.Backends` was for but I'm still getting my round-robin test setup.

**Comment by martin-helmich** [comment]
Hey Zach, thanks for your feedback! I wouldn't be opposed to adding an additional `-varnish-service` flag (or similarly named). There may be a use case for adding the option to watch more services in the future, but in that case I would probably prefer having those be configurable via a ConfigMap or Custom Resource instead of adding more command line flags.

Would you be willing to provide a Pull Request for this feature?

>Also, it wasn't clear to me what .PrimaryBackend vs .Backends was for but I'm still getting my round-robin test setup.

The `.PrimaryBackend` vs. `.Backend` option was introduced to accomodate an edge case we had with a stateful legacy application, which needed to have a subset of its traffic routed to a single endpoint. The `.PrimaryBackend` will be filled with a randomly selected endpoint from the backend service and remain constant as long as that Pod exists.

**Comment by znorris** [comment]
Thank you for explaining `.PrimaryBackend` 👍.

> Would you be willing to provide a Pull Request for this feature?

I'd certainly be willing to take a stab at it. However, it may be another week or two before I have the time.

**Comment by dealancer** [comment]
I am going to implement a Varnish cluster with a following manual: https://info.varnish-software.com/blog/creating-self-routing-varnish-cluster.

Thinking about ways to workaround this with and existing codebase. I am curious, can we use an existing `.Backends` for varnish backends, while setting a hardcoded name of service for the origin deployment in the VCL file?

**Comment by martin-helmich** [comment]
@dealancer The workaround should -- in theory -- be possible. However, when you use a Kubernetes service name as backend in your VCL file, you rely on Kubernetes service load-balancing (which is basically some arcane iptables black magic) and subsequently use some of the load balancing features that Varnish offers (like choosing your load balancing algorithm, host health checks, sticky sessions, and so on). If you don't require these features for your setup, this might work.

**Comment by dealancer** [comment]
@martin-helmich just tried this workaround and that worked, and you are right, the load balancing to the app is done through the Kubernetes, not Varnish in this case.

**Comment by dealancer** [comment]
@martin-helmich now I understand that for HA cluster, we need to support ban requests which should be broadcasted to multiple nodes. There is a Varnish Broadcaster, but it needs to be included into a Varnish container to work correctly: https://info.varnish-software.com/blog/introducing-varnish-broadcaster-for-cache-invalidation

**Comment by martin-helmich** [comment]
@dealancer Using Varnish Broadcaster was a possible solution we discussed for #11 (along with some other possible solutions, if you're interested). My issue with Varnish Broadcaster was that it's not Open Source, making it difficult to integrate into this project.

A Broadcaster integration would have to be contributed by someone with access to Varnish Plus (which I don't have) and even then we couldn't provide a Docker image containing it (and even then I'd be hesitant to accept a contribution because I have no way to test, i.e. maintain it). 🤷‍♂

**Comment by dealancer** [comment]
@martin-helmich please review my PR, this PR solves current issue, also makes it easier to implement #11.

**Comment by dealancer** [comment]
@martin-helmich I have added compatibility enhancements, now it should be ok.
